// 1:1 call signaling — Firestore is the transport (no separate signaling
// server), same philosophy as the rest of this app (see lib/db.js). This
// module is pure Firestore I/O; the WebRTC plumbing lives in lib/webrtc.js
// and the two are glued together by lib/useCall.js.
//
// See firestore.rules `match /calls/{callId}` for the server-enforced state
// machine this file writes into.

import {
  addDoc, collection, deleteDoc, doc, getDocs, onSnapshot, orderBy, query,
  serverTimestamp, setDoc, updateDoc, where,
} from 'firebase/firestore'
import { db } from './firebase'
import { newId } from './storage'
import { dmConvoId } from './db'

export const callPairKey = (a, b) => [a, b].sort().join('__')

const ACTIVE_STATES = ['ringing', 'accepted']

// Firestore composite-index errors on these listeners fail *silently* from
// the UI's point of view (onSnapshot just never delivers data again) unless
// we log something — same soft-fail pattern as the mentions query in
// lib/notifications.jsx, but that one already has a console hint; these
// didn't, which is exactly what made an early bug report ("nothing
// happened after granting permission") hard to diagnose.
function logListenerError(name, err) {
  console.error(`[calls] ${name} listener failed:`, err)
  if (err?.code === 'failed-precondition') {
    console.info(
      `[calls] Firestore wants a composite index for "${name}". Open the URL ` +
      'in the error above and click "Create index" — until then this listener ' +
      'will never deliver data.'
    )
  }
}

// A fresh call id, generated by the caller *before* signaling starts so it
// can be wired into RTCPeerConnection callbacks with no race window (see
// lib/useCall.js) — never reuse dmConvoId here, a pair may call repeatedly.
export const newCallId = () => newId()

// Caller only.
export async function createCall({ callId, callerUid, calleeUid, offer }) {
  await setDoc(doc(db, 'calls', callId), {
    members: [callerUid, calleeUid].sort(),
    callerUid,
    calleeUid,
    dmConvoId: dmConvoId(callerUid, calleeUid),
    pairKey: callPairKey(callerUid, calleeUid),
    type: 'video', // audio+video together in v1; kept for future audio-only mode
    state: 'ringing',
    offer,
    answer: null,
    createdAt: serverTimestamp(),
    acceptedAt: null,
    endedAt: null,
    endedBy: null,
  })
  return callId
}

// Callee only.
export async function acceptCall(callId, answer) {
  await updateDoc(doc(db, 'calls', callId), {
    state: 'accepted',
    answer,
    acceptedAt: serverTimestamp(),
  })
}

const endWith = (callId, state, byUid) =>
  updateDoc(doc(db, 'calls', callId), { state, endedAt: serverTimestamp(), endedBy: byUid })

export const declineCall = (callId, byUid) => endWith(callId, 'declined', byUid) // callee only
export const cancelCall  = (callId, byUid) => endWith(callId, 'cancelled', byUid) // caller only
export const markMissed  = (callId, byUid) => endWith(callId, 'missed', byUid)    // caller only
export const endCall     = (callId, byUid) => endWith(callId, 'ended', byUid)     // either member
export const markFailed  = (callId, byUid) => endWith(callId, 'failed', byUid)    // either member

export async function sendIceCandidate(callId, fromUid, candidate) {
  await addDoc(collection(db, 'calls', callId, 'candidates'), {
    from: fromUid,
    candidate,
    createdAt: serverTimestamp(),
  })
}

// Single call-doc listener (drives the local state-machine reaction).
export function listenCall(callId, cb, onError) {
  return onSnapshot(
    doc(db, 'calls', callId),
    snap => cb(snap.exists() ? { id: snap.id, ...snap.data() } : null),
    err => { logListenerError('listenCall', err); onError?.(err) },
  )
}

// Fires once per newly-added candidate (not the whole set each time) so the
// caller can just addIceCandidate() incrementally.
export function listenIceCandidates(callId, onAdd, onError) {
  const q = query(collection(db, 'calls', callId, 'candidates'), orderBy('createdAt', 'asc'))
  return onSnapshot(
    q,
    snap => {
      snap.docChanges().forEach(change => {
        if (change.type === 'added') onAdd({ id: change.doc.id, ...change.doc.data() })
      })
    },
    err => { logListenerError('listenIceCandidates', err); onError?.(err) },
  )
}

// Best-effort; a call doc is kept as history but its candidates aren't.
export async function cleanupCallCandidates(callId) {
  try {
    const snap = await getDocs(collection(db, 'calls', callId, 'candidates'))
    await Promise.all(snap.docs.map(d => deleteDoc(d.ref)))
  } catch (e) {
    console.warn('[calls] candidate cleanup failed (non-fatal):', e.message)
  }
}

// All non-terminal calls between me and one specific peer — used for the
// pre-call glare/rejoin check (see lib/useCall.js).
export function listenActiveCallForPeer(myUid, otherUid, cb, onError) {
  const q = query(
    collection(db, 'calls'),
    where('pairKey', '==', callPairKey(myUid, otherUid)),
    where('state', 'in', ACTIVE_STATES),
  )
  return onSnapshot(
    q,
    snap => cb(snap.docs.map(d => ({ id: d.id, ...d.data() }))),
    err => { logListenerError('listenActiveCallForPeer', err); onError?.(err) },
  )
}

// All of my non-terminal calls (any peer) — usually 0 or 1, occasionally 2
// for an instant during mutual-call glare. Sorted by id so consumers can
// deterministically pick the same "winner" independently on both ends
// without any coordination (see lib/useCall.js for the reconciliation).
export function listenMyActiveCall(myUid, cb, onError) {
  const q = query(
    collection(db, 'calls'),
    where('members', 'array-contains', myUid),
    where('state', 'in', ACTIVE_STATES),
  )
  return onSnapshot(
    q,
    snap => {
      const calls = snap.docs.map(d => ({ id: d.id, ...d.data() }))
      calls.sort((a, b) => a.id.localeCompare(b.id))
      cb(calls)
    },
    err => { logListenerError('listenMyActiveCall', err); onError?.(err) },
  )
}

// Best-effort cleanup of my own stale outbound `ringing` calls (e.g. a tab
// that crashed mid-call before its no-answer timer could fire) so they don't
// block future glare/busy checks forever. Call once per session on load.
const STALE_RINGING_MS = 60_000
export async function sweepStaleOutboundCalls(myUid) {
  try {
    const q = query(
      collection(db, 'calls'),
      where('callerUid', '==', myUid),
      where('state', '==', 'ringing'),
    )
    const snap = await getDocs(q)
    const now = Date.now()
    await Promise.all(snap.docs.map(d => {
      const createdMs = d.data().createdAt?.toMillis?.() ?? 0
      return (now - createdMs > STALE_RINGING_MS) ? markMissed(d.id, myUid) : null
    }))
  } catch (e) {
    console.warn('[calls] stale-call sweep failed (non-fatal):', e.message)
  }
}
