import 'package:cloud_firestore/cloud_firestore.dart';

import '../models/call.dart';
import '../utils/firestore_paths.dart';
import 'id_gen.dart';

/// 1:1 port of the 1:1-call signaling functions in src/lib/calls.js.
/// Firestore is the signaling transport — see firestore.rules
/// `match /calls/{callId}` for the server-enforced state machine this writes
/// into.
class CallsRepository {
  CallsRepository({FirebaseFirestore? firestore})
    : _db = firestore ?? FirebaseFirestore.instance;
  final FirebaseFirestore _db;

  static const _activeStates = Call.activeStates;

  String pairKey(String a, String b) {
    final sorted = [a, b]..sort();
    return sorted.join('__');
  }

  /// A fresh call id, generated by the caller *before* signaling starts so
  /// it can be wired into RTCPeerConnection callbacks with no race window
  /// (see providers/calls_providers.dart) — never reuse dmConvoId, a pair
  /// may call repeatedly.
  String newCallId() => newId();

  /// `type` is 'audio' or 'video' — determines whether the caller's (and
  /// later the callee's) local stream requests a camera track.
  Future<void> createCall({
    required String callId,
    required String callerUid,
    required String calleeUid,
    required Map<String, dynamic> offer,
    String type = 'video',
  }) async {
    await _db.collection('calls').doc(callId).set({
      'members': [callerUid, calleeUid]..sort(),
      'callerUid': callerUid,
      'calleeUid': calleeUid,
      'dmConvoId': dmConvoId(callerUid, calleeUid),
      'pairKey': pairKey(callerUid, calleeUid),
      'type': type,
      'state': 'ringing',
      'offer': offer,
      'answer': null,
      'createdAt': FieldValue.serverTimestamp(),
      'acceptedAt': null,
      'endedAt': null,
      'endedBy': null,
    });
  }

  Future<void> acceptCall(String callId, Map<String, dynamic> answer) {
    return _db.collection('calls').doc(callId).update({
      'state': 'accepted',
      'answer': answer,
      'acceptedAt': FieldValue.serverTimestamp(),
    });
  }

  Future<void> _endWith(String callId, String state, String byUid) {
    return _db.collection('calls').doc(callId).update({
      'state': state,
      'endedAt': FieldValue.serverTimestamp(),
      'endedBy': byUid,
    });
  }

  Future<void> declineCall(String callId, String byUid) =>
      _endWith(callId, 'declined', byUid); // callee only
  Future<void> cancelCall(String callId, String byUid) =>
      _endWith(callId, 'cancelled', byUid); // caller only
  Future<void> markMissed(String callId, String byUid) =>
      _endWith(callId, 'missed', byUid); // caller only
  Future<void> endCall(String callId, String byUid) =>
      _endWith(callId, 'ended', byUid); // either member
  Future<void> markFailed(String callId, String byUid) =>
      _endWith(callId, 'failed', byUid); // either member

  Future<void> sendIceCandidate(
    String callId,
    String fromUid,
    Map<String, dynamic> candidate,
  ) {
    return _db.collection('calls').doc(callId).collection('candidates').add({
      'from': fromUid,
      'candidate': candidate,
      'createdAt': FieldValue.serverTimestamp(),
    });
  }

  /// Single call-doc listener (drives the local state-machine reaction).
  Stream<Call?> listenCall(String callId) {
    return _db
        .collection('calls')
        .doc(callId)
        .snapshots()
        .map((snap) => snap.exists ? Call.fromDoc(snap) : null);
  }

  /// Fires once per newly-added candidate (not the whole set each time).
  Stream<CallCandidate> listenIceCandidates(String callId) {
    return _db
        .collection('calls')
        .doc(callId)
        .collection('candidates')
        .orderBy('createdAt')
        .snapshots()
        .expand(
          (snap) => snap.docChanges
              .where((c) => c.type == DocumentChangeType.added)
              .map((c) => CallCandidate.fromDoc(c.doc)),
        );
  }

  // ---------- Mid-call renegotiation (e.g. audio call -> add video) ----------
  //
  // Adding a track to an already-connected RTCPeerConnection requires a
  // fresh SDP offer/answer round — it can't reuse the call doc's original
  // offer/answer fields.

  /// Marks the call itself as video — read reactively by both sides' UI so
  /// a mid-call upgrade shows the video area/camera controls for both
  /// parties even before the SDP exchange below finishes.
  Future<void> upgradeCallToVideo(String callId) {
    return _db.collection('calls').doc(callId).update({'type': 'video'});
  }

  Future<String> proposeRenegotiation(
    String callId,
    String fromUid,
    Map<String, dynamic> offer,
  ) async {
    final ref = await _db
        .collection('calls')
        .doc(callId)
        .collection('renegotiate')
        .add({
          'from': fromUid,
          'offer': offer,
          'answer': null,
          'createdAt': FieldValue.serverTimestamp(),
        });
    return ref.id;
  }

  Future<void> answerRenegotiation(
    String callId,
    String negId,
    Map<String, dynamic> answer,
  ) {
    return _db
        .collection('calls')
        .doc(callId)
        .collection('renegotiate')
        .doc(negId)
        .update({'answer': answer});
  }

  /// Fires for every add/change to a renegotiation doc — the caller (see
  /// providers/calls_providers.dart) decides whether it's an incoming offer
  /// to answer or the answer to an offer it sent.
  Stream<CallRenegotiation> listenRenegotiations(String callId) {
    return _db
        .collection('calls')
        .doc(callId)
        .collection('renegotiate')
        .orderBy('createdAt')
        .snapshots()
        .expand(
          (snap) => snap.docChanges
              .where((c) => c.type != DocumentChangeType.removed)
              .map((c) => CallRenegotiation.fromDoc(c.doc)),
        );
  }

  /// Best-effort; a call doc is kept as history but its candidates aren't.
  Future<void> cleanupCallCandidates(String callId) async {
    try {
      final snap = await _db
          .collection('calls')
          .doc(callId)
          .collection('candidates')
          .get();
      await Future.wait(snap.docs.map((d) => d.reference.delete()));
    } catch (_) {
      // non-fatal
    }
  }

  /// All of my non-terminal calls (any peer) — usually 0 or 1, occasionally
  /// 2 for an instant during mutual-call glare. Sorted by id so both ends
  /// deterministically pick the same "winner" with no coordination (see
  /// providers/calls_providers.dart for the reconciliation).
  Stream<List<Call>> listenMyActiveCall(String myUid) {
    return _db
        .collection('calls')
        .where('members', arrayContains: myUid)
        .where('state', whereIn: _activeStates)
        .snapshots()
        .map((snap) {
          final calls = snap.docs.map(Call.fromDoc).toList()
            ..sort((a, b) => a.id.compareTo(b.id));
          return calls;
        });
  }

  /// Best-effort cleanup of my own stale outbound `ringing` calls (e.g. a
  /// killed app that never got to fire its no-answer timer) so they don't
  /// block future glare/busy checks forever. Call once per session start.
  static const _staleRingingMs = 60000;

  Future<void> sweepStaleOutboundCalls(String myUid) async {
    try {
      final snap = await _db
          .collection('calls')
          .where('callerUid', isEqualTo: myUid)
          .where('state', isEqualTo: 'ringing')
          .get();
      final now = DateTime.now().millisecondsSinceEpoch;
      await Future.wait(
        snap.docs.map((d) {
          final createdMs =
              (d.data()['createdAt'] as Timestamp?)?.millisecondsSinceEpoch ??
              0;
          return (now - createdMs > _staleRingingMs)
              ? markMissed(d.id, myUid)
              : Future.value();
        }),
      );
    } catch (_) {
      // non-fatal
    }
  }
}
